# Generated by Django 5.2 on 2025-06-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='num',
            field=models.IntegerField(default=7),
        ),
    ]
