# Generated by Django 5.2 on 2025-06-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='num',
        ),
    ]
